name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'Cargo.lock'
      - 'src/**'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'Cargo.lock'
      - 'src/**'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ${{ matrix.config.platform }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - platform: ubuntu-latest
            target: 'x86_64-unknown-linux-gnu'
            name: 'Linux x86_64'
          - platform: ubuntu-latest
            target: 'aarch64-unknown-linux-gnu'
            name: 'Linux ARM64'
          - platform: ubuntu-latest
            target: 'armv7-unknown-linux-gnueabihf'
            name: 'Linux ARMv7'

          - platform: macos-latest
            target: 'x86_64-apple-darwin'
            name: 'macOS x86_64'
          - platform: macos-latest
            target: 'aarch64-apple-darwin'
            name: 'macOS ARM64'

          - platform: windows-latest
            target: 'x86_64-pc-windows-msvc'
            name: 'Windows x86_64'
          - platform: windows-latest
            target: 'aarch64-pc-windows-msvc'
            name: 'Windows ARM64'
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Add target
        run: rustup target add ${{ matrix.config.target }}

      - name: (Linux ARM64) Install dependencies
        if: matrix.config.platform == 'ubuntu-latest' && (matrix.config.target == 'aarch64-unknown-linux-gnu' || matrix.config.target == 'armv7-unknown-linux-gnueabihf')
        run: sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: (Linux ARMv7) Install dependencies
        if: matrix.config.platform == 'ubuntu-latest' && matrix.config.target == 'armv7-unknown-linux-gnueabihf'
        run: sudo apt-get install -y gcc-arm-linux-gnueabihf

      - name: (Linux ARM64) Add C compiler to PATH
        if: matrix.config.platform == 'ubuntu-latest' && matrix.config.target == 'aarch64-unknown-linux-gnu'
        # This must be added to $GITHUB_PATH (see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path)
        run: echo "/usr/bin/aarch64-linux-gnu-gcc" >> $GITHUB_PATH

      # Also add the C++ compiler
      - name: (Linux ARM64) Add C++ compiler to PATH
        if: matrix.config.platform == 'ubuntu-latest' && matrix.config.target == 'aarch64-unknown-linux-gnu'
        # This must be added to $GITHUB_PATH (see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path)
        run: echo "/usr/bin/aarch64-linux-gnu-g++" >> $GITHUB_PATH

      - name: (Linux ARMv7) Add C compiler to PATH
        if: matrix.config.platform == 'ubuntu-latest' && matrix.config.target == 'armv7-unknown-linux-gnueabihf'
        # This must be added to $GITHUB_PATH (see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path)
        run: echo "/usr/bin/arm-linux-gnueabihf-gcc" >> $GITHUB_PATH

      # Also add the C++ compiler
      - name: (Linux ARMv7) Add C++ compiler to PATH
        if: matrix.config.platform == 'ubuntu-latest' && matrix.config.target == 'armv7-unknown-linux-gnueabihf'
        # This must be added to $GITHUB_PATH (see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path)
        run: echo "/usr/bin/arm-linux-gnueabihf-g++" >> $GITHUB_PATH

      - name: (Linux) Install dependencies
        if: matrix.config.platform == 'ubuntu-latest'
        run: sudo apt-get install -y xorg-dev

      - name: Build
        run: cargo build --target ${{ matrix.config.target }} --release
        env:
          RUSTFLAGS: -Awarnings

      - name: (Unix) Upload binary
        if: matrix.config.platform != 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Deppo ${{ matrix.config.name }}
          path: target/${{ matrix.config.target }}/release/deppo

      - name: (Windows) Upload binary
        if: matrix.config.platform == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Deppo ${{ matrix.config.name }}
          path: target/${{ matrix.config.target }}/release/deppo.exe