name: Lint

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - 'Cargo.lock'
      - 'src/**'
      - 'rustfmt.toml'
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - 'Cargo.lock'
      - 'src/**'
      - 'rustfmt.toml'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0

jobs:
  rustfmt:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8
        with:
          components: rustfmt

      - name: Rustfmt check
        run: cargo fmt --all -- --check

      # also check updater
      - name: Rustfmt check updater
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8
        with:
          components: clippy

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Clippy check
        run: cargo clippy -- -D warnings

      # Also clippy check updater
      - name: Clippy check updater
        run: cargo clippy -- -D warnings
